### ISSUE TITLE
Proxy Error 499/502

### ISSUE THREAD

**Issue by Falco82it** [joshkunz/tumblr2rss#15]
The link created by the site (https://tumblr2rss.obstack.net/) gives me this error:
"Proxy error 499" (QuiteRSS) or "502 Proxy Error" (Firefox)

When you open the site on Firefox its ok, but if click the button "Login with tumblr" it appears: 

"Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server"

**Comment by 27arts** [comment]
same issue for the last two days.

**Comment by joshkunz** [comment]
Looks like there were some upstream issues with the tumblr API that put the server in a weird state. I re-booted it and it appears to be working again. I'm not seeing anything that looks like server errors in the logs. Please re-open if the re-occurs.

**Comment by joshkunz** [comment]
Note to future self: I was able to repro the issue, and was able to generate a new RSS feed URL after rebooting.
