### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by DrGaellon** [joshkunz/tumblr2rss#4]
When trying to register with the "Login with Tumblr" button, I get an error page that says "Bad request. The browser (or proxy) sent a request that this server could not understand."

**Comment by postprefix** [comment]
same

**Comment by joshkunz** [comment]
Tumblr started re-directing their auth endpoints to https, which the oath2 library didn't like. The issue should now be fixed.

Sorry it took me so long to get to this one.
