### ISSUE TITLE
502 Proxy Error

### ISSUE THREAD

**Issue by Falco82it** [joshkunz/tumblr2rss#6]
After accessing Tumblr via tumblr2rss.obstack.net, the browser show this error:

"Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /registered.

Reason: Error reading from remote server"

**Comment by joshkunz** [comment]
Thanks for the bug report!

I've got a fix working locally. I'll push it out tomorrow.
